app/src/main/java/me/ash/reader/ui/page/home/feeds/option/feed/FeedOptionDrawer.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/option/feed/FeedOptionViewModel.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/ResultView.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Pops up a dialog with a text field allowing editing of the feed url
Design/implementation is the same as editing feed name- click on the feed url and a dialog is shown
Not purging articles from old URL when updating the URL btw. Can do that if desired, lmk
And missing chinese translation for "Feed URL", feel free to edit that or let me know what I should put there

Allow feed URL to be edited

---

app/build.gradle
app/src/main/java/me/ash/reader/ui/ext/ScrollbarsExt.kt
app/src/main/java/me/ash/reader/ui/page/home/read/ReadPage.kt
app/src/main/java/me/ash/reader/ui/page/home/read/ReadViewModel.kt

Showing a scrollbar is very useful for me when reading long articles. Helps estimate how much time an article will take to read and how much time is left.
**Some implementation notes:**
This PR pulls in the `androidx.compose.ui:ui-util` dependency for the `List.fastSumBy { }` function in `ScrollBarsExt.kt`. `fastSumBy` can be replaced with `List.sumOf { }` if you want to avoid pulling in another dep, but I'm assuming it gives some perf boost and r8 will shake out unused code.
Had to replace LazyColumn with Column because LazyColumn doesn't expose full scroll state. I'm a compose novice but I don't think this should cause any perf issues, since the list is static. (but notably, it's harder to jumpToItem with column so I ripped it out instead of reimplementing it)

Add a scrollbar to the article screen

---

app/src/main/res/values-pl/strings.xml
fastlane/metadata/android/pl/full_description.txt
fastlane/metadata/android/pl/short_description.txt

Added a Polish translation. 
In Polish there is a different form for certain plurals (when there are 2,3 or 4 items). I put them separately **but the form for two, three and four is the same:**
I am not a programmer, but after looking at the existing translations I think such a solution should work. If there is a better way to do it please correct it.

Added Polish translation

---

app/src/main/java/me/ash/reader/ui/component/reader/HtmlToComposable.kt

The image in some feeds like Politico or Substack cannot be displayed in Feeder and Read You.
The change is the same as [this commit](https://gitlab.com/spacecowboy/Feeder/-/commit/8e662118dc5844f09ce84e805bd26915627b9d5e) in Feeder.

Fix parsing of srcset images

---

app/src/main/java/me/ash/reader/data/model/account/AccountType.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/AddAccountsPage.kt
app/src/main/res/values/strings.xml

Feedly is written as Feedlly in the app. The domain in the app with the double `l` also redirects to an advertisment domain, instead of the correct https://feedly.com
This PR fixes the string values and variable names.

Rename Feedlly to the correct name of Feedly

---

.github/workflows/build_commit.yaml
.github/workflows/build_pull_request.yaml

Warnings like Node.js and set-output are gone.

Updated Workflow-Files because of Warnings

---

app/build.gradle
app/src/main/AndroidManifest.xml

This migration is done by the [AGP Upgrade Assistant](https://developer.android.google.cn/studio/build/agp-upgrade-assistant)

chore: move package from Android Manifest to build files

---

app/build.gradle
app/src/main/java/me/ash/reader/ui/component/base/FeedbackIconButton.kt
app/src/main/java/me/ash/reader/ui/component/base/RYOutlineTextField.kt
app/src/main/java/me/ash/reader/ui/component/base/RYTextField.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedItem.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/SearchBar.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/TopBar.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/feeds/FeedsPagePreview.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/flow/FlowPagePreview.kt
app/src/main/java/me/ash/reader/ui/page/settings/tips/TipsAndSupportPage.kt
build.gradle

Upgrade Material to 1.0.1 version could make ripple effect more resonable, and brings more ui components, but it caused some components updateded, only WARN level.
Refer #369 
Some problems still, when you switch "Always Expand" off, preview will show background in grey color.

Bump Material to 1.0.1 version and fix "Always Expand" preview

---

app/src/main/java/me/ash/reader/ui/component/reader/Styles.kt
app/src/main/java/me/ash/reader/ui/theme/Theme.kt
app/src/main/java/me/ash/reader/ui/theme/Type.kt

Add RTL support to `Typography` & `TextStyle`s

---

app/src/main/java/me/ash/reader/data/model/general/MarkAsReadConditions.kt
app/src/main/java/me/ash/reader/data/repository/FeverRssRepository.kt

This PR implements two separate fixes for the issues outlined in #398. Building Read You with these changes fixes the "Mark as Read" buttons on my environment.
Here are the details:
As detailed in the [original docs](https://feedafever.com/api), the Fever API requires a `before` parameter (formatted as a Unix timestamp) in requests to update a feed or category as read (`before` a certain time). My prior understanding was that this is meant to be represented in seconds; the [Wikipedia entry](https://en.wikipedia.org/wiki/Unix_time) for Unix time and some of my own investigations [1][2][3] support this. Most applications (including popular Fever endpoints) seem to expect seconds.
Read You, however, appears to send the Fever `before` parameter as _milliseconds_ instead of seconds. This …

Fix: "Mark as Read" buttons don't work (#398)

---

app/src/main/AndroidManifest.xml

Hey thanks for the great app!
Small thing - apps targeting API 33 must add declare the notification permission, otherwise they will not be able to post notifications, see the documentation here https://developer.android.com/develop/ui/views/notifications/notification-permission
This PR just adds the permission so users can manually allow the permission, but the app should also request this permission at run-time so the user can accept it too. If you give me a heads up on how you want to do it I can make a PR for that too if you like. 
This should fix https://github.com/Ashinch/ReadYou/issues/407

Add notification permission

---

app/src/main/java/me/ash/reader/MainActivity.kt

On some devices, the navigation bar still displays a not transparent overlay cover after using `WindowCompat.setDecorFitsSystemWindows(window, false)`. This pull request make navigation bar fully transparent.
在一些系统中，像OneUI、MIUI之类的，即使使用了`WindowCompat.setDecorFitsSystemWindows(window, false)`，导航栏仍然会显示一层不完全透明的遮罩。这个pull request可以使导航栏在这些系统中完全透明。

Make navigation bar transparent in more devices.

---

app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsViewModel.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingPage.kt

#346
第一个问题表现在于ReadingPage中的LaunchedEffect在每次compose中都会collect当前路由传参articleId，会导致一次页面的重新加载，解决方法就是仅在articleId不同时才刷新。
第二个问题改用ViewModel以及StateFlow保存状态即可，目前只是修复了分组的展开、收起的状态保存，至于列表的滚动，改动可能不小，等我有空再改吧。

Fix ReadingPage recompose after returning from other page.(#346)

---

app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt

This PR is for https://github.com/Ashinch/ReadYou/pull/455, which implemented a swipe to mark articles as read. In the original pull request, we get a gray tint over the article item, but I found that this did not look good. I made it apply to the current theme, which looks universal and clean.
It's nice to finally have it implemented, but we need to limit it to 'unread' flow only, and make the article list reload after a small delay (say 20-30 ms) to make it smoother, since we don't have the list animation after a swipe that refreshes right after a gesture dismiss. I hope it will get your attention and we will make it work as smooth as expected. 
Cheers, and thanks @boun for such a great PR! Can't wait for a release :D

Make the item swipe design more universal

---

app/proguard-rules.pro

#507
When refactoring the code, I overlooked modifying the `proguard-rules.pro` file, resulting in the obfuscation of the Fever API-related code. This eventually manifested as normal operation in Debug mode but triggered authentication errors in Release mode.

fix(fever): authentication failure

---

app/src/main/java/me/ash/reader/infrastructure/android/MainActivity.kt

The bug described in #312 is longstanding, and quite annoying - the only workaround is for users to delete all articles in the affected source and move on, but that's not ideal (articles may be missed).
From recent research into the topic, it [seems like this is a broader Android problem](https://github.com/andpor/react-native-sqlite-storage/issues/364) and not unique to Read You. Fortunately, that also means people have found fixes!
With the help of @kermes in the Read You issue, I was able to consistently reproduce the bug using the source `https://www.newtral.es/feed/`. After applying the fix suggested in the thread above, the bug no longer happens on that feed! :tada: 
@Ashinch said in the Read You bug thread that it may also be a paging issue, so we probably shouldn't consider this a …

Add workaround for "Row too big to fit into CursorWindow" bug

---

app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt

After some digging into #515, I think I've figured out the root cause of the various issues with "swipe to mark as read" marking unrelated items as read.
Internally, Read You has a `markAsRead` function that is called when a part of the app wants to mark an article as read. It takes a few parameters: either a group ID, feed ID, or article ID. It would take appropriate action depending on which ID was provided.
Now, an unwritten assumption of this bit of code was that _only one of the IDs would be supplied to `markAsRead` at once_. This assumption was violated by the swipe to dismiss code, which provided _all three_. This manifested as various inconsistent behavior throughout the app, especially on the Fever API - which has additional mark as read code.
The fix is simple: make sure the …

Fix swipe gesture attempting to mark feeds and groups as read

---

app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt

(cherry picked from commit c35fe96d0c453b733ec4a7a813244c7b4b47b026)

only swipe to remove artile with unread filter

---

app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt

Currently, we don't have the option to mark as unread by swiping left, so `SwipeableArticleItem` is unnecessary when the article has been read.
(Mainly because I haven't found a way to increase the swipe friction, **and the default friction factor makes it easy for users to accidentally trigger it.**)
In order to give `SwipeableArticleItem` the features of Material You, I have redesigned it. The new design may not be very friendly to languages with long characters.

refactor(ui): redesign swipe mark as read for article item

---

app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt
app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt
app/src/main/java/me/ash/reader/domain/service/AccountService.kt
app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/infrastructure/html/Readability.kt
app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt
app/src/main/java/me/ash/reader/infrastructure/rss/provider/greader/GoogleReaderAPI.kt
app/src/main/java/me/ash/reader/infrastructure/rss/provider/greader/GoogleReaderDTO.kt

refactor(greader): incrementally fetch the unread items by last sync time

---

app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/infrastructure/di/OkHttpClientModule.kt

This is a reference to Reeder's synchronization logic, which syncs well across multiple devices. The following link contains other great synchronization logic, but it was not adopted due to the solidified domain model of this application.
During the initial synchronization, it fetches all articles from the past month to provide users with a better multi-device experience. However, during subsequent synchronizations (`n`-th time), it only fetches items that have differences between the local device and the server, reducing network requests. Currently, the synchronization time is mainly blocked on replacing the database records of subscription list, which can be addressed later by revising the model. The primary method of data exchange currently relies on in-memory operations, which might …

refactor(greader): incrementally fetch the unread items by difference set

---

app/build.gradle
app/proguard-rules.pro
app/src/main/java/me/ash/reader/infrastructure/android/NotificationHelper.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/SearchBar.kt
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- Migrate to [Compose BOM](https://developer.android.com/jetpack/compose/bom), and update Compose dependencies to Compose BOM 2023.10.01
- Update Compose compiler to 1.5.7 (requires Kotlin 1.9.21)
- Update Kotlin to 1.9.21
- Update a bunch of dependencies (hilt, coil, okhttp, room, accompanist, lifecycle)
- Update Android Gradle Plugin to 8.2.1, and Gradle to 8.0
- Update `compileSdk` to 34 (not `tragetSdk`)
- Changes are made to source to pass the lint check
> [!Note]
Potential breaking changes and bugs may probably occur during usage. Please test these changes carefully before merging this PR, or consider publishing an alpha release.

build(deps): bump up dependencies, compile sdk, and gradle version

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/me/ash/reader/infrastructure/android/MainActivity.kt
app/src/main/java/me/ash/reader/infrastructure/preference/LanguagesPreference.kt
app/src/main/res/resources.properties

- Migrate to AndroidX support library for [in-app language picker](https://developer.android.com/guide/topics/resources/app-languages#androidx-impl)
- Add support for [Per-app language preferences](https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig) in system settings (Blocked by #502)

fix(i18n): configuration loss when switching locale

---

app/build.gradle
app/src/main/java/me/ash/reader/infrastructure/android/MainActivity.kt
app/src/main/java/me/ash/reader/infrastructure/preference/LanguagesPreference.kt
app/src/main/java/me/ash/reader/ui/page/settings/SettingsPage.kt
app/src/main/java/me/ash/reader/ui/page/settings/languages/LanguagesPage.kt
app/src/main/res/values/strings.xml

- Add all languages whose translation progress exceeds 50% in [Hosted Weblate](https://hosted.weblate.org/projects/readyou/android-strings/) to the in-app language picker
- Modify the display order according to their language codes
- A little bit modifications to avoid possible confusion ^^;
Expected behaviors:
-  Android 12 and below, in-app language picker works as expected
-  Android 13 and above, changes made to app language from **system settings or in-app language picker** should align with the other one.

feat(i18n): add languages to in-app language picker

---

app/build.gradle
app/src/main/java/me/ash/reader/ui/component/reader/HtmlToComposable.kt
app/src/main/java/me/ash/reader/ui/component/reader/Reader.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/Content.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/ReaderImagePage.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingPage.kt

Close #545 
Close #372 
Implementation details:
- Use `zoomable()` modifier from https://github.com/saket/telephoto for zoom and pan images
- Use a full screen `Dialog` to open a modal window (the neatest workaround I can think of before we can achieve shared element transition in Compose)
Maybe we should add an option for saving the image too
CC @nvllz 
Screen record:
<details>
https://github.com/Ashinch/ReadYou/assets/69683722/7840cc42-76bb-42df-aeb6-80b364868f27
</details>

feat(ui): show full screen image viewer when clicking on images

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/me/ash/reader/infrastructure/android/CrashHandler.kt
app/src/main/java/me/ash/reader/infrastructure/android/CrashReportActivity.kt
app/src/main/res/values/strings.xml

Currently, the app handles uncaught exceptions using toast message, which is somehow hard to read and notice by user. This PR adds a fullscreen Activity to display error information and prompt users to go to Github to submit a bug report.
Here's what it looks like:
<details>
</details>

feat(ui): add crash report activity to handle uncaught exceptions

---

app/src/main/java/me/ash/reader/infrastructure/preference/Preference.kt
app/src/main/java/me/ash/reader/infrastructure/preference/Settings.kt
app/src/main/java/me/ash/reader/infrastructure/preference/SwipeActionPreference.kt
app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/FlowViewModel.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/SwipeToDismissBox.kt
app/src/main/java/me/ash/reader/ui/page/settings/interaction/InteractionPage.kt
app/src/main/res/values/strings.xml

Also migrate from MD2 `SwipeDismiss` to MD3 `SwipeToDismissBox`, should fix some visual glitches like #506 
cc @nvllz 
Close #194
Close #586

feat(ui): swipe to star/unstar, swipe to unread

---

app/src/main/java/me/ash/reader/ui/page/home/flow/SearchBar.kt

Fix alignment of placeholder text and add an ellipsis for overflowed texts
| Before  | After |
| ------------- | ------------- |
| ![Reader-1-before](https://github.com/Ashinch/ReadYou/assets/10359255/9af175a4-e292-4258-a729-d56bc65f91ec)  | ![Reader-1-after](https://github.com/Ashinch/ReadYou/assets/10359255/8f03a2d4-ba27-4a78-9458-9f05dd2bd4f9) |

fix(ui): fix alignment of search bar placeholder text

---

app/src/main/java/me/ash/reader/ui/ext/DateExt.kt

Instead of adding an option to configure the time format, this PR make the time to be formatted according to the app's locale and the system's 12-/24-hour clock preference.
Examples:
- 24-hour format for Japan/US: `13:00`
- 12-hour format for Japan: `午後1:30` (instead of `1:30 午後` when using `hh:mm a` for formatting)
- 12-hour format for US: `1:30 PM`
Close #98

feat(ui): format time with system locale default

---

app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt

1. remove `fetchArticles` since `changeFilter` internally invokes that
2. call `changeFilter` only when filter changes
Before
https://github.com/Ashinch/ReadYou/assets/10359255/4ee7d27a-a871-4100-800a-3340c4796f70
After
https://github.com/Ashinch/ReadYou/assets/10359255/0822df07-d4dc-4589-8ebd-3f6f215815b5

fix(ui): fetch articles only when filter changes

---

app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt
app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt
app/src/main/java/me/ash/reader/ui/ext/DateExt.kt

fix(sync): replace publish date of an article with the current time if it is a future date

---

app/src/main/java/me/ash/reader/ui/component/FilterBar.kt
app/src/main/java/me/ash/reader/ui/component/base/BlockButton.kt
app/src/main/java/me/ash/reader/ui/component/base/RYScaffold.kt
app/src/main/java/me/ash/reader/ui/ext/ColorScheme.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/TopBar.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/ColorAndStylePage.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/feeds/FeedsPagePreview.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/flow/FlowPagePreview.kt
app/src/main/java/me/ash/reader/ui/theme/palette/DynamicTonalPalette.kt

What does this PR do:
- Migrate to the new [tone-based surfaces in MD3](https://material.io/blog/tone-based-surface-color-m3)
- Fix the bug where tonal elevation preferences doesn't work in some components
To Do:

refactor(ui): migrate to tone-based surfaces in MD3

---

app/build.gradle
app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt
app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/ui/component/menu/AnimatedDropdownMenu.kt
app/src/main/java/me/ash/reader/ui/component/menu/DropdownMenuImpl.kt
app/src/main/java/me/ash/reader/ui/motion/MaterialEasing.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/FlowViewModel.kt
app/src/main/res/values/strings.xml
build.gradle

A walkaround or add-on before we implement #585 
Close #611 
To Do:

feat(ui): long press on an item to show context menu

---

app/src/main/java/me/ash/reader/infrastructure/preference/Preference.kt
app/src/main/java/me/ash/reader/infrastructure/preference/ReadingTextLineHeightPreference.kt
app/src/main/java/me/ash/reader/infrastructure/preference/Settings.kt
app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt
app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingPage.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/reading/ReadingTextPage.kt
app/src/main/java/me/ash/reader/ui/page/settings/color/reading/TitleAndTextPreview.kt
app/src/main/res/values/strings.xml

feat(ui): add line height multiple preference for reading page

---

app/src/main/java/me/ash/reader/domain/service/OpmlService.kt

fix(opml): ignore default group non-null check for service accounts when export

---

app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt

fix(rss): first find the enclosure tag as a thumbnail

---

app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt

This has been a pet peeve of mine when using the Greader API: categories/folders aren't sorted alphabetically when in the Feeds view. The way the app works today, categories are arranged by whichever category has the _feed_ with the lowest lexicographical order, which is very unintuitive.
As an example, let's say I have the following categories and feeds:
```json
"Apples": {
"feeds": ["Fruits of the Day"]
},
"Bananas": {
"feeds": ["A banana a day keeps the doctor away"]
},
```
Under the current code, these categories get ordered as:
```
Bananas
Apples
```
because `A banana a day keeps the doctor away` is lexicographically before `Fruits of the Day`.
While it's true that we should probably implement some way to allow the user to manually reorder feeds, this is a quick fix that requires …

feat(greader): sort categories alphabetically during sync

---

app/src/main/java/me/ash/reader/infrastructure/preference/FlowArticleListDateStickyHeaderPreference.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt

About this PR:
- Fix performance & data loading issues with sticky headers disabled
- Disable sticky headers by default
Related issues:
https://issuetracker.google.com/u/1/issues/193785330 
https://stackoverflow.com/questions/67649953/sticky-headers-with-paging-library-in-jetpack-compose

fix(ui): fix performance & data loading issues with sticky headers disabled

---

app/src/main/java/me/ash/reader/infrastructure/preference/NewVersionSizePreference.kt
app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt

In earlier versions, there was an `Int` type named `newVersionSize`. In version `0.10.0`, `newVersionSizeString` was renamed back to `newVersionSize`, causing a conversion error for earlier users when converting from `Int` to `String` type values, leading to application crashes and startup failures.
Close #730

fix(preferences): revert `newVersionSize` to `newVersionSizeString`

---

app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/ui/ext/NumberExt.kt

Replace `NullPointerException` with `IllegalArgumentException`, generating human-readable stacktraces

chore(greader): add null checks in greader service

---

app/src/main/java/me/ash/reader/ui/component/base/Banner.kt
app/src/main/java/me/ash/reader/ui/component/base/DisplayText.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt

Closes https://github.com/Ashinch/ReadYou/issues/685.
Removed the fixed height of the banner and adjusted padding to compensate. Fix cut synchronization text as well.
<details>
<\details>

fix(ui): Prevent text from being cut off in banner

---

app/src/main/java/me/ash/reader/infrastructure/rss/BestIconFinder.kt
app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt
app/src/main/java/me/ash/reader/ui/component/FeedIcon.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedItem.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/drawer/feed/FeedOptionDrawer.kt
app/src/main/java/me/ash/reader/ui/page/home/feeds/drawer/feed/FeedOptionViewModel.kt
app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt

fix(rss): fetch best icon

---

app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt

feat(ui): preserve search state in flow page

---

app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt

slightly speed up(~50% of the previous implementation) the sync process for large feed list (>16)

feat(sync): sync feeds concurrently

---

app/src/main/java/me/ash/reader/domain/model/account/security/FeverSecurityKey.kt
app/src/main/java/me/ash/reader/domain/model/account/security/FreshRSSSecurityKey.kt
app/src/main/java/me/ash/reader/domain/model/account/security/GoogleReaderSecurityKey.kt
app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt
app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt
app/src/main/java/me/ash/reader/infrastructure/di/OkHttpClientModule.kt
app/src/main/java/me/ash/reader/infrastructure/rss/provider/ProviderAPI.kt
app/src/main/java/me/ash/reader/infrastructure/rss/provider/fever/FeverAPI.kt
app/src/main/java/me/ash/reader/infrastructure/rss/provider/greader/GoogleReaderAPI.kt
app/src/main/java/me/ash/reader/ui/component/base/RYOutlineTextField.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/addition/AddFeverAccountDialog.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/addition/AddFreshRSSAccountDialog.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/addition/AddGoogleReaderAccountDialog.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/connection/FeverConnection.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/connection/FreshRSSConnection.kt
app/src/main/java/me/ash/reader/ui/page/settings/accounts/connection/GoogleReaderConnection.kt
app/src/main/res/values/strings.xml

Using a reverse-proxy with [mTLS (client authentication)](https://en.wikipedia.org/wiki/Mutual_authentication) is a [decent way](https://dominikbritz.com/posts/secure-remote-access/#create-a-certificate-authority) to expose your self-hosted services on the internet.
This PR adds support for using a certificate that's [installed in your Android device](https://support.google.com/pixelphone/answer/2844832?hl=en).
The changes are largely based on:
- This Photoprism client: https://github.com/Radiokot/photoprism-android-client/pull/14
- This sample: https://github.com/diebietse/mtls-android
An optional client certificate can be selected when adding self-hosted accounts (FreshRSS, Google Reader and Fever APIs):
It can later be changed/removed when viewing the account details:
I'm comfortable …

Support specifying a client certificate for mTLS auth

---

app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedOptionView.kt

The alignment for the new group button is wrong in the feed menu. This PR fixes it so that the button is in-line vertically with the other buttons.
Before:
After:

Fix new group button alignment

---

app/src/main/java/me/ash/reader/infrastructure/rss/FetchedFeed.kt

The commit https://github.com/Ashinch/ReadYou/commit/ec05bddba8e435482dadbda7d8ca645749e257ba introduced a regression where attempting to subscribe to a feed without a favicon will cause ReadYou to crash. The link to the icon should be set to null if one doesn't exist, just like it did before the commit.
I used the following feed to test this bug:
https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss

Fix the crash that occurs when adding a feed without an icon

---

README-de.md
README-zh-CN.md
README.md
app/src/main/java/me/ash/reader/ui/component/webview/WebViewHtml.kt
app/src/main/java/me/ash/reader/ui/component/webview/WebViewScript.kt
app/src/main/java/me/ash/reader/ui/component/webview/WebViewStyle.kt

The current bionic reading implementation struggles with edge cases such as chained-together words.
By replacing the bionic reading JS with the well-tested (and GPL-licensed) code from [Jiffy Reader](https://github.com/ansh/jiffyreader.com), we can avoid issues like this and open the door to further improvements (such as allowing the fixation strength and saccades interval to be customized or allowing bionic reading to be toggled without a reload)

Improve handling of edge cases when using bionic reading
