ReadYouApp/ReadYou

app/src/main/java/me/ash/reader/data/preference/AmoledDarkThemePreference.kt, app/src/main/java/me/ash/reader/data/preference/DarkThemePreference.kt, app/src/main/java/me/ash/reader/data/preference/Settings.kt, app/src/main/java/me/ash/reader/ui/component/DynamicSVGImage.kt, app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt, app/src/main/java/me/ash/reader/ui/page/common/HomeEntry.kt, app/src/main/java/me/ash/reader/ui/page/common/RouteName.kt, app/src/main/java/me/ash/reader/ui/page/home/read/ReadPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/SettingItem.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/ColorAndStyle.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/DarkTheme.kt, app/src/main/java/me/ash/reader/ui/theme/Theme.kt, app/src/main/java/me/ash/reader/ui/theme/palette/DynamicTonalPalette.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Add dark theme settings

app/src/main/java/me/ash/reader/ui/page/home/FilterBar.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/ColorAndStyle.kt, app/src/main/java/me/ash/reader/ui/theme/Theme.kt, app/src/main/java/me/ash/reader/ui/theme/palette/DynamicTonalPalette.kt, app/src/main/java/me/ash/reader/ui/theme/palette/TonalPalettes.kt, app/src/main/java/me/ash/reader/ui/theme/palette/dynamic/WallpaperColors.kt
=> Replace the first palette with the color scheme provided by the system

app/build.gradle, app/src/main/java/me/ash/reader/App.kt, app/src/main/java/me/ash/reader/ui/page/settings/tips/TipsAndSupport.kt, app/src/main/java/me/ash/reader/ui/page/settings/tips/UpdateViewModel.kt
=> Add GitHub and F-droid flavors

app/src/main/java/me/ash/reader/ui/component/AsyncImage.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt
From: [Feeder](https://gitlab.com/spacecowboy/Feeder/-/commit/7eb2d0f81003a392aafc614010f1856e42cddb78)
#77
=> Fixed crash if loading very large (50MB+) images

app/src/main/java/me/ash/reader/data/model/preference/LanguagesPreference.kt, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
Hey! Added Russian translation, I hope you find it useful and accept my PR
=> Added russian translation

app/src/main/java/me/ash/reader/ui/ext/LazyListStateExt.kt
Maybe this is a spelling mistake
=> fix a scroll bug

README-fa.md
Hello, I had mistakenly don't remove some English lines in the translation and did not link to the original README. This PR solves these problems. ThankYou
=> fix persian README issue

app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
This is my first Pull-Request so i dont really know if it is right what i am doing.
I implemented the Monochrome Icon for Android 13.
=> Monochrome Icon

app/src/main/java/me/ash/reader/data/repository/FeverRssRepository.kt
Very minor typo introduced in #399, but it was highlighted by Android Studio so I'm gonna fix it :sweat_smile:
=> Fix a var that should have been a val in #399

app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt
This pull request implements a means of swiping articles out of the article list in order to mark them read.
=> Implement Swipe to mark read

app/src/main/java/me/ash/reader/ui/page/home/reading/BottomBar.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/TopBar.kt
Implement enhancement issue #447
1. Fix issue that BottomBar's navigationBarsPadding is transparent.
2. Change TopBar background to MaterialTheme.colorScheme.surface.
=> Implement enhancement issue #447

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/me/ash/reader/data/model/preference/OpenLinkPreference.kt, app/src/main/java/me/ash/reader/data/model/preference/OpenLinkSpecificBrowserPreference.kt, app/src/main/java/me/ash/reader/data/model/preference/Preference.kt, app/src/main/java/me/ash/reader/data/model/preference/Settings.kt, app/src/main/java/me/ash/reader/ui/component/base/WebView.kt, app/src/main/java/me/ash/reader/ui/component/reader/Reader.kt, app/src/main/java/me/ash/reader/ui/ext/ContextExt.kt, app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/drawer/feed/FeedOptionDrawer.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/Content.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/Metadata.kt, app/src/main/java/me/ash/reader/ui/page/settings/interaction/InteractionPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/languages/LanguagesPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/tips/TipsAndSupportPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/tips/UpdateDialog.kt, app/src/main/res/values/strings.xml
This option let us chose the browser when link on clicked in feeds.
There are 5 options
* Auto (Prefer CustomTabs) - default option
* Auto (Prefer Default Browser)
* Force CustomTabs
* Force default browser
* Force specific browser (need to choice browser App)
We can set this option: "Settings" -> "Interaction" -> "App when link clicked"
=> [Feature Request]Add OpenLink Option

app/build.gradle, fastlane/metadata/android/en-US/changelogs/20.txt
=> Update version 0.9.9

app/src/main/java/me/ash/reader/ui/component/base/Base64Image.kt, app/src/main/res/values/strings.xml
1. fix svg base64 parsing.
2. fix a typo.
=> Fix fever favicon failed to parse when it's SVG

app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleItem.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/ArticleList.kt
fix https://github.com/Ashinch/ReadYou/issues/515
=> fix swipe to mark read article issue

app/build.gradle, fastlane/metadata/android/en-US/changelogs/20.txt, fastlane/metadata/android/en-US/changelogs/21.txt, fastlane/metadata/android/en-US/changelogs/22.txt
=> Update version 0.9.11

app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt
fix https://github.com/Ashinch/ReadYou/issues/446 and https://github.com/Ashinch/ReadYou/issues/469
=> fix NPE cased by absent article title when subscribing feed with local account

app/src/main/java/me/ash/reader/ui/ext/NavGraphBuilderExt.kt, app/src/main/java/me/ash/reader/ui/motion/MaterialSharedAxis.kt, app/src/main/java/me/ash/reader/ui/motion/MotionConstants.kt, app/src/main/java/me/ash/reader/ui/page/common/HomeEntry.kt
=> feat(ui): use forward and backward transition

app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt, app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt, app/src/main/java/me/ash/reader/infrastructure/rss/provider/greader/GoogleReaderAPI.kt, app/src/main/java/me/ash/reader/ui/page/home/HomeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/drawer/feed/FeedOptionViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/drawer/group/GroupOptionViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/FlowViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingViewModel.kt, app/src/main/java/me/ash/reader/ui/page/settings/accounts/AccountViewModel.kt
=> fix(greader): mark all as read

app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt, app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt, app/src/main/java/me/ash/reader/infrastructure/rss/provider/greader/GoogleReaderAPI.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeDialog.kt, app/src/main/java/me/ash/reader/ui/page/settings/accounts/AccountViewModel.kt
=> fix(greader): handle group stream id

app/src/main/AndroidManifest.xml, app/src/main/java/me/ash/reader/infrastructure/android/MainActivity.kt, app/src/main/java/me/ash/reader/ui/page/common/HomeEntry.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeViewModel.kt
Close #436
i know this is ugly but i can't find a more elegant way
=> feat(ui): add feed via system share sheet

app/src/main/java/me/ash/reader/ui/ext/DateExt.kt, app/src/main/java/me/ash/reader/ui/page/settings/accounts/AccountDetailsPage.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, build.gradle
=> fix(opml): bump opml-parser to 3.1.0 and re-design OPML export dialog

app/src/main/AndroidManifest.xml, app/src/main/java/me/ash/reader/infrastructure/android/AndroidApp.kt, app/src/main/java/me/ash/reader/infrastructure/storage/AndroidImageDownloader.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/ReaderImagePage.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingPage.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingViewModel.kt, app/src/main/res/values/strings.xml
About this PR:
- Human-readable implementation
- No new dependency introduced
- Scoped storage best practice
- No need for `WRITE_EXTERNAL_STORAGE` permission on Android 10 (API 29) or above
Close #372
=> feat(ui): save image as file

app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt, app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/infrastructure/rss/provider/fever/FeverAPI.kt
=> fix(rss): ignore starred articles by default when clean feed or group

app/src/main/java/me/ash/reader/infrastructure/preference/Preference.kt, app/src/main/java/me/ash/reader/infrastructure/preference/Settings.kt, app/src/main/java/me/ash/reader/infrastructure/preference/SharedContentPreference.kt, app/src/main/java/me/ash/reader/ui/ext/ContextExt.kt, app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt, app/src/main/java/me/ash/reader/ui/ext/StringExt.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/TopBar.kt, app/src/main/java/me/ash/reader/ui/page/settings/accounts/AccountViewModel.kt, app/src/main/java/me/ash/reader/ui/page/settings/interaction/InteractionPage.kt, app/src/main/res/values/strings.xml
=> feat(reading): support for specifying the composition of shared content

app/src/main/java/me/ash/reader/domain/service/AccountService.kt, app/src/main/java/me/ash/reader/infrastructure/android/CrashReportActivity.kt, app/src/main/java/me/ash/reader/ui/ext/ContextExt.kt, app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt, app/src/main/java/me/ash/reader/ui/ext/FileEXT.kt, app/src/main/java/me/ash/reader/ui/ext/StringExt.kt, app/src/main/java/me/ash/reader/ui/page/common/HomeEntry.kt, app/src/main/java/me/ash/reader/ui/page/common/RouteName.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeDialog.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/settings/SettingsPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/accounts/AccountDetailsPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/troubleshooting/TroubleshootingPage.kt, app/src/main/java/me/ash/reader/ui/page/settings/troubleshooting/TroubleshootingViewModel.kt, app/src/main/res/values/strings.xml
=> feat(settings): add troubleshooting page and app preferences import/export tool

.github/FUNDING.yml, README-de.md, README.md
=> docs: remove invalid sponsorship links

app/build.gradle, app/src/main/java/me/ash/reader/infrastructure/android/CrashReportActivity.kt, app/src/main/java/me/ash/reader/infrastructure/android/MainActivity.kt, app/src/main/java/me/ash/reader/ui/page/common/HomeEntry.kt
Androidx has been officailly implemented edge to edge, with more powerful compatibility.
https://developer.android.com/develop/ui/compose/layouts/insets?hl=zh-cn#insets-setup
=> feat(ui): switch to androidx edge to edge implementation

app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt
Closes https://github.com/Ashinch/ReadYou/issues/682, closes https://github.com/Ashinch/ReadYou/issues/96.
<details>
</details>
=> Do not display `Default` group in feeds list if it is empty

app/src/main/java/me/ash/reader/domain/service/OpmlService.kt, app/src/main/java/me/ash/reader/infrastructure/rss/OPMLDataSource.kt, app/src/main/java/me/ash/reader/ui/ext/StringExt.kt, app/src/test/java/me/ash/reader/infrastructure/rss/OPMLDataSourceTest.kt, app/src/test/java/me/ash/reader/ui/ext/StringExtKtTest.kt
=> test(opml): empty title

.github/workflows/testing.yml
Related to #783
Adds a new GitHub Actions workflow to enforce unit tests on every pull request to the main branch.
- **Workflow Configuration**: Introduces `testing.yml` in the `.github/workflows` directory, activating on pull requests targeting the main branch.
- **Testing Environment Setup**: Configures the workflow to run on the latest Ubuntu version, sets up JDK 17, and executes `./gradlew test` to run unit tests.
- **Automatic Test Enforcement**: Ensures that pull requests cannot be merged unless all unit tests pass, enhancing code quality and preventing regressions. (To block the merge when the action fails, the repository owner must set a rule in the repository settings)
=> ci: Enforce unit tests on every pull request

app/src/main/java/me/ash/reader/ui/component/base/RYAsyncImage.kt
=> feat(ui): add referer header with domain extraction for image proxying

app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt, app/src/test/java/me/ash/reader/infrastructure/rss/RssHelperTest.kt
=> fix(rss): get enclosure from SyndEntry attributes first

app/src/main/java/me/ash/reader/ui/page/home/reading/ReaderImagePage.kt
Close #773.
- On tap: Close window
- On long tap: Expand menu (e.g., save)
=> feat(ui): enhance ReaderImageViewer Interactive gestures

app/src/main/java/me/ash/reader/ui/page/home/reading/Content.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/PullToLoad.kt
=> fix(ui): webview renderer nested scrolling

app/src/main/java/me/ash/reader/ui/component/webview/RYWebView.kt, app/src/main/java/me/ash/reader/ui/component/webview/WebViewLayout.kt, app/src/main/java/me/ash/reader/ui/component/webview/WebViewStyle.kt
=> fix(reader): make webview align with reading font family

app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedItem.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/GroupItem.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/accounts/AccountsTab.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/feeds/FeedsPagePreview.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/feeds/FeedsPageStylePage.kt, app/src/main/java/me/ash/reader/ui/theme/Theme.kt, app/src/main/java/me/ash/reader/ui/theme/palette/DynamicTonalPalette.kt, app/src/main/java/me/ash/reader/ui/theme/palette/FixedColorRoles.kt
- Migrate existing containers to the new tone-based surfaces
- Add `FixedColorRoles`
- Fix color contrast for a few components
Fix #888
=> feat(ui): fine-tune colors 

app/src/main/java/me/ash/reader/ui/page/home/flow/FlowPage.kt
=> fix(ui): commit diffs before running in background

app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/domain/service/SyncWorker.kt, app/src/main/java/me/ash/reader/infrastructure/android/AndroidApp.kt, app/src/main/java/me/ash/reader/ui/page/home/HomeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/flow/FlowViewModel.kt
=> fix(sync): refactor `SyncWorker` for robust background sync

app/build.gradle.kts
=> fix: user agent in build config

app/build.gradle.kts, app/proguard-rules.pro, app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/domain/service/FeverRssService.kt, app/src/main/java/me/ash/reader/domain/service/GoogleReaderRssService.kt, app/src/main/java/me/ash/reader/infrastructure/android/AndroidApp.kt, app/src/main/java/me/ash/reader/infrastructure/di/NostrClientModule.kt, app/src/main/java/me/ash/reader/infrastructure/rss/FetchedFeed.kt, app/src/main/java/me/ash/reader/infrastructure/rss/OPMLDataSource.kt, app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt, app/src/main/java/me/ash/reader/ui/ext/StringExt.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeDialog.kt, app/src/main/java/me/ash/reader/ui/page/home/feeds/subscribe/SubscribeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingViewModel.kt, app/src/test/java/me/ash/reader/infrastructure/rss/RssHelperTest.kt, gradle/libs.versions.toml
This PR adds support for [Nostr feeds](https://github.com/nostr-protocol/nips/blob/master/23.md). For more info about Nostr, it can be checked out [here](https://github.com/nostr-protocol/nostr).
Nostr feed support includes adding a feed using a nostr URI(`nostr:...`), or importing a feed containing Nostr URIs.
A demo of Nostr feed support is shown below:
https://github.com/user-attachments/assets/3cc75164-ba5e-4c0b-97f1-b0bad3df2f81
Thanks for your work on the app!
=> Nostr feed support.

app/src/main/java/me/ash/reader/ui/page/home/reading/ReadingViewModel.kt
=> Scroll back to last seen item(from unread list)

app/src/main/java/me/ash/reader/domain/repository/ArticleDao.kt, app/src/main/java/me/ash/reader/domain/service/AbstractRssRepository.kt, app/src/main/java/me/ash/reader/infrastructure/android/AndroidApp.kt, app/src/main/java/me/ash/reader/infrastructure/preference/Preference.kt, app/src/main/java/me/ash/reader/infrastructure/preference/Settings.kt, app/src/main/java/me/ash/reader/infrastructure/preference/SettingsProvider.kt, app/src/main/java/me/ash/reader/infrastructure/preference/SortUnreadItemsPreference.kt, app/src/main/java/me/ash/reader/ui/ext/DataStoreExt.kt, app/src/main/java/me/ash/reader/ui/page/home/HomeViewModel.kt, app/src/main/java/me/ash/reader/ui/page/settings/color/flow/FlowPageStylePage.kt, app/src/main/java/me/ash/reader/ui/page/settings/interaction/InteractionPage.kt, app/src/main/res/values/strings.xml
=> feat: sort unread items by lastest/earliest

app/src/main/res/values-zh-rCN/strings.xml
remove zh_cn deprecated update_link, use universal link
=> fix: remove deprecated zh_cn update link
